// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04TIw2bCmui5AfwRQr6pSf89MBOXKyDM',
    appId: '1:489825321370:web:9697b319b32bef9c9cba23',
    messagingSenderId: '489825321370',
    projectId: 'aunt-flo-3',
    authDomain: 'aunt-flo-3.firebaseapp.com',
    storageBucket: 'aunt-flo-3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDv_-vZGFMkNLSCX0nrV5-KUGunn_PwZM',
    appId: '1:489825321370:android:1c1d491b5d4532cf9cba23',
    messagingSenderId: '489825321370',
    projectId: 'aunt-flo-3',
    storageBucket: 'aunt-flo-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFodhsdp8KvuWEBqaxodUO2JOqvk_S24',
    appId: '1:489825321370:ios:8c5271af9132704f9cba23',
    messagingSenderId: '489825321370',
    projectId: 'aunt-flo-3',
    storageBucket: 'aunt-flo-3.appspot.com',
    iosBundleId: 'com.example.auntFlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArFodhsdp8KvuWEBqaxodUO2JOqvk_S24',
    appId: '1:489825321370:ios:de12c5fb02a08e399cba23',
    messagingSenderId: '489825321370',
    projectId: 'aunt-flo-3',
    storageBucket: 'aunt-flo-3.appspot.com',
    iosBundleId: 'com.example.auntFlo.RunnerTests',
  );
}
